more towards automated job cleanup.

diff --git a/rr-job-prep b/rr-job-prep
--- a/rr-job-prep
+++ b/rr-job-prep
@@ -19,7 +19,7 @@
 
 ################################################################################
 ################################################################################
-# ONLY TESTED ON RR-LIKE SYSTEMS WITH PBS!
+#         ONLY TESTED ON RR-LIKE SYSTEMS WITH PBS AND OPEN MPI 1.4.3!          #
 ################################################################################
 ################################################################################
 
@@ -28,17 +28,48 @@ declare -r PROG_VER="0.1"
 declare -r CRUNCH_NAME="crunch-hang"
 declare -r ALL_NODES_FN="ALL"
 declare -r SUBSET_NODES_FN="SUB"
+declare -r SMGC_OUT_FN="OUT"
+
+# items to be run on exit
+declare -a on_exit_items
 
 # this will eventually be set to a real value, but set to a safe default
 tmp_base="/tmp"
+# job id
 jobid="unknown"
+# pid of killer - start with something bogus and relatively harmless
+killer_pid=$$
 
 # in seconds
-#KILL_TIMEOUT=360
-KILL_TIMEOUT=4
+#declare -r KILL_TIMEOUT=300
+declare -r KILL_TIMEOUT=4
 
 ################################################################################
-usage()
+################################################################################
+# exit/cleanup code
+################################################################################
+################################################################################
+function on_exit()
+{
+    for i in "${on_exit_items[@]}"; do
+        #echo "on_exit: $i"
+        eval "$i" 2>&1 > /dev/null
+    done
+}
+
+################################################################################
+function add_on_exit()
+{
+    local n=${#on_exit_items[*]}
+    on_exit_items[$n]="$*"
+    if [[ $n -eq 0 ]]; then
+        #echo "setting trap"
+        trap on_exit EXIT
+    fi
+}
+
+################################################################################
+function usage()
 {
 cat << EOF
 Usage:
@@ -52,10 +83,11 @@ EOF
 }
 
 ################################################################################
-run_and_pray()
+function run_and_pray()
 {
     ( mpirun --hostfile "$tmp_base/$SUBSET_NODES_FN" \
-    "$1" -t small_all_to_all_ptp 2>&1 | tee "$tmp_base/OUT" 2>&1 > /dev/null )&
+    "$1" -t small_all_to_all_ptp 2>&1 | \
+    tee "$tmp_base/$SMGC_OUT_FN" 2>&1 > /dev/null )&
     cmd_pid=$!
 
     # setup the killer
@@ -70,15 +102,16 @@ run_and_pray()
         echo "### RUN TIMEOUT EXCEEDED. this may mean we can't launch mpi jobs."
         echo "### please contact the system administrators."
         echo "### JOBID: $jobid"
-        # not much else we can do here...
+        # not much else we can do here... well, maybe that's not true, but it
+        # is a little harder to deal with
         exit 1;
     else
         # "normal" exit, so clean up - we still don't know if things worked.
         disown $killer_pid
-        kill $killer_pid &> /dev/null
+        kill $killer_pid 2>&1 > /dev/null
     fi
 
-    local crunch_out=`$2 "$tmp_base/OUT"`
+    local crunch_out=`$2 "$tmp_base/$SMGC_OUT_FN"`
 
     if [[ "x$crunch_out" == "x### NO HANG ###" ]]; then
         echo "### successful run - found a good set!"
@@ -91,7 +124,7 @@ run_and_pray()
 }
 
 ################################################################################
-find_good_node_set()
+function find_good_node_set()
 {
     echo "### starting - cross your fingers ###"
     echo
@@ -105,7 +138,17 @@ find_good_node_set()
 }
 
 ################################################################################
-hello()
+function have_jobid()
+{
+    if [[ "x$PBS_JOBID" == "x" ]]; then
+        echo 0
+    else
+        echo 1
+    fi
+}
+
+################################################################################
+function hello()
 {
 cat << EOF
 ### $PROG_NAME $PROG_VER ###
@@ -113,11 +156,17 @@ EOF
 }
 
 ################################################################################
-init()
+function init()
 {
     echo "# starting init..."
-    jobid="$PBS_JOBID"
+    if [[ `have_jobid` -eq 1 ]]; then
+        jobid="$PBS_JOBID"
+    else
+        echo "cannot determine job id"
+        exit 1;
+    fi
     tmp_base=`mktemp -d -t SMGCXXXX`
+    echo "# timeout: $KILL_TIMEOUT s"
     echo "# temp directory: $tmp_base"
     echo "# copying $PBS_NODEFILE file to $tmp_base"
     # save a copy of the full list of nodes and start with a full set
@@ -126,6 +175,14 @@ init()
     if [[ $? != 0 ]]; then
         echo "cp failure!"
         exit 1;
+    else
+        # add cleanup code
+        add_on_exit rm -f "$tmp_base/$ALL_NODES_FN"
+        add_on_exit rm -f "$tmp_base/$SUBSET_NODES_FN"
+        add_on_exit rm -f "$tmp_base/$SMGC_OUT_FN"
+        add_on_exit rmdir "$tmp_base"
+        add_on_exit killall -q -9 mpirun
+        add_on_exit killall -q -9 supermagic
     fi
 }
 
@@ -133,7 +190,7 @@ init()
 # $1: path to supermagic
 # $2: path to crunch-hang
 # will exit with status 1 if app/env prerequisites are not met.
-sanity()
+function sanity()
 {
     local the_base=$(basename "$1")
     # check for mpirun
